[tox]
envlist = py38, py312
#, py310, py38  # Test in Python 3.12 (add more like py39, py310 if needed)
isolated_build = True  # Ensures clean builds
skip_missing_interpreters = True

[testenv]
# Commands to run in each env
commands =
    # Run your tests with pytest
    pytest -v

# Dependencies for the test env
deps =
    pytest
    pytest-mock